### ISSUE TITLE
Unable to Hearthstone

### ISSUE THREAD

**Issue by dreadnought101** [omghixd/Path-of-Classic-Bugtracker#163] opened 2020-11-28 22:16 UTC
It may be because I took a boat across the ocean and messed with the cd, unsure.

![Unable to Hearthstone](https://user-images.githubusercontent.com/10070048/100527139-bcf09d00-318c-11eb-90dc-a4fb49ba0837.PNG)

**Comment by omghixd** [comment] 2020-11-28 22:21
Attempt to relog or delete the hearthstone and set your home elsewhere at an inkeeper to get a new one.

It is quite difficult to say what the cause is.

**Comment by dreadnought101** [comment] 2020-11-28 22:22
At the moment, simply waiting fixed the issue, but unsure.  Will try to reproduce later.

**Comment by omghixd** [comment] 2020-11-28 22:38
Most likely just a visual bug removing the capability of seeing the cooldown timer. I'll go ahead and close this then. if it happens again just re-open =)

**Closed by omghixd** 2020-11-28 22:38 UTC
