### ISSUE TITLE
[NPC] The Direglob - Prime Slime Quest

### ISSUE THREAD

**Issue by Tyrvana** [omghixd/Path-of-Classic-Bugtracker#169] opened 2020-11-28 23:53 UTC
Quest/Spell/Item/Creature(ID) The ID is: 26490

The Current Behaviour is as following: Does not move, attack. Does not drop Quest Item, only junk.

Expected Behaviour should be as following: Attack player & moving, drop Quest item

Screenshot/Video (IMGUR/YOUTUBE): 
https://youtu.be/3nZTRvnXC0w?t=29
Additional Information:
**Creature type says: Not specified**
https://www.wowhead.com/quest=26490/prime-slime

**Comment by omghixd** [comment] 2020-11-29 02:45
Direglob will now attack you once you attack it.

And it will also drop [Direglob Sample] https://www.wowhead.com/item=58082/direglob-sample as intended

//Fixed and closing this report.

**Closed by omghixd** 2020-11-29 02:45 UTC
